### ISSUE TITLE
Vision page

### ISSUE THREAD

**Issue by finozzifa** [open-energy-transition/handbook#74]
Write the [Vision](https://open-energy-transition.github.io/handbook/docs/Company/Vision) page.

Please refer to the [Editing the Handbook](https://open-energy-transition.github.io/handbook/docs/Handbook/EditingTheHandbook) page and [Handbook style guide](https://open-energy-transition.github.io/handbook/docs/Handbook/HandbookStyleGuide) for guidance.

**Comment by drifter089** [comment]
#160
