### ISSUE TITLE
What we do page

### ISSUE THREAD

**Issue by finozzifa** [open-energy-transition/handbook#90]
Write the [What We Do](https://open-energy-transition.github.io/handbook/docs/Engineering/WhatWeDo) page.

Please refer to the [Editing the Handbook](https://open-energy-transition.github.io/handbook/docs/Handbook/EditingTheHandbook) page and [Handbook style guide](https://open-energy-transition.github.io/handbook/docs/Handbook/HandbookStyleGuide) for guidance.

**Comment by drifter089** [comment]
#159
